#!/bin/bash
filename=""
if [ -n "$1" ]; then
    filename="$1"
else
    filename="./bytecodes/temp.m"
fi

./comp
if [ $? = 0 ]; then
    valgrind --leak-check=full --show-leak-kinds=all ./monty "$filename"
fi
